import grpc
from concurrent import futures
import time
from ...infrastructure.di import get_tasks_handler, get_create_task_handler
from ...application.queries.get_tasks import GetTasksQuery
from ...application.commands.create_task import CreateTaskCommand
import asyncio

# Assuming these are generated by protoc
# import task_pb2
# import task_pb2_grpc

class TaskServiceServicer: # This would inherit from task_pb2_grpc.TaskServiceServicer
    async def GetTasks(self, request, context):
        handler = get_tasks_handler()
        query = GetTasksQuery(limit=request.limit, offset=request.offset)
        tasks_data = await handler.handle(query)
        
        # response = task_pb2.GetTasksResponse()
        # for t in tasks_data:
        #     response.tasks.add(id=t['id'], title=t['title'], ...)
        # return response
        return {"tasks": tasks_data}

    async def CreateTask(self, request, context):
        handler = get_create_task_handler()
        command = CreateTaskCommand(title=request.title, project_id=request.project_id)
        task_id = await handler.handle(command)
        return {"task_id": task_id, "status": "accepted"}

async def serve():
    server = grpc.aio.server()
    # task_pb2_grpc.add_TaskServiceServicer_to_server(TaskServiceServicer(), server)
    server.add_insecure_port('[::]:50051')
    await server.start()
    await server.wait_for_termination()
